<script type="text/javascript">function jspoosearch()
    {
        if(jspoo.url01.checked)
            window.open("http://api.bbbbbb.me/jx/?url="+jspoo.key.value,"");
        if(jspoo.url02.checked)
            window.open("https://jx.dy-jx.com/?url="+jspoo.key.value,"");
        if(jspoo.url03.checked)
            window.open("http://jx.598110.com/?url="+jspoo.key.value,"");
        if(jspoo.url04.checked)
            window.open("http://api.sumingys.com/index.php?url="+jspoo.key.value,"");
        if(jspoo.url05.checked)
            window.open("http://www.82190555.com/video.php?url="+jspoo.key.value,"");
        if(jspoo.url06.checked)
            window.open("http://api.uuyingshi.com/?url="+jspoo.key.value,"");
        if(jspoo.url07.checked)
            window.open("http://api.nepian.com/ckparse/?url="+jspoo.key.value,"");
        if(jspoo.url08.checked)
            window.open("http://jx.ejiafarm.com/dy.php?url="+jspoo.key.value,"");
        if(jspoo.url09.checked)
            window.open("http://jiexi.071811.cc/jx.php?url="+jspoo.key.value,"");
        if(jspoo.url10.checked)
            window.open("https://vip.mpos.ren/v/?url="+jspoo.key.value,"");
        if(jspoo.url11.checked)
            window.open("http://api.wlzhan.com/sudu/?url="+jspoo.key.value,"");
        if(jspoo.url12.checked)
            window.open("http://jqaaa.com/jx.php?url="+jspoo.key.value,"");
        if(jspoo.url13.checked)
            window.open("http://api.lequgirl.com/?url="+jspoo.key.value,"");
        if(jspoo.url14.checked)
            window.open("http://jx.598110.com/index.php?url="+jspoo.key.value,"");
        if(jspoo.url15.checked)
            window.open("http://aikan-tv.com/?url="+jspoo.key.value,"");
        if(jspoo.url16.checked)
            window.open("http://app.baiyug.cn:2019/vip/index.php?url="+jspoo.key.value,"");
        if(jspoo.url17.checked)
            window.open("http://17kyun.com/api.php?url="+jspoo.key.value,"");
        if(jspoo.url18.checked)
            window.open("http://api.hlglwl.com/jx.php?url="+jspoo.key.value,"");
        if(jspoo.url19.checked)
            window.open("http://jx.hanximeng.com/api.php?url="+jspoo.key.value,"");
        if(jspoo.url20.checked)
            window.open("http://api.52xmw.com/?url="+jspoo.key.value,"");
        if(jspoo.url21.checked)
            window.open("https://jx.618g.com/?url="+jspoo.key.value,"");
        if(jspoo.url22.checked)
            window.open("http://okjx.cc/?url="+jspoo.key.value,"");
        return false;
    }</script>
